apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: chuck-norris-streams-filter
  name: chuck-norris-streams-filter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chuck-norris-filter
    spec:
      containers:
      - name: chuck-norris-filter
        image: quay.io/lbroudoux/chuck-norris-filter:latest
        env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap.amq-streams.svc.cluster.local:9092
        - name: MOVIES_SOURCE_TOPIC
          value: remysqldb.movie
        - name: CUSTOMERS_SOURCE_TOPIC
          value: mysqldb.customer
        - name: RENTALS_SOURCE_TOPIC
          value: mysqldb.customer
        - name: TARGET_TOPIC
          value: rental-chuck-norris